# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment Mappings
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Base Properties
mc_version=1.21.1
minecraft_version_range=[1.20.6,1.21.2)
neo_version=21.1.197
neo_version_range=[21,)
loader_version_range=[2,)

# Mod Properties
mod_id=psionic_relics
mod_name=Psionic Relics
mod_license=MIT
mod_version=1.0.1
mod_group_id=dev.qther.psionic_relics
mod_authors=Qther
mod_description=Relics for Psi.

# Dependencies
# See https://www.curseforge.com/minecraft/mc-mods/psi/files/all?page=1&pageSize=20
psi_cursemaven_tag=6815563
# See https://maven.blamejared.com/mezz/jei/
jei_version=19.21.0.247
# See https://mvnrepository.com/artifact/vazkii.patchouli/Patchouli
patchouli_version=1.21-87
# See https://maven.theillusivec4.top/top/theillusivec4/curios/curios-neoforge/
curios_version=9.5.1